### ISSUE TITLE
Error 1.15.2 papermc

### ISSUE THREAD

**Issue by car1ot** [MrMicky-FR/FastParticles#3]
[17:29:58` WARN]: [MoneyItemsRain] Task #50 for MoneyItemsRain v1.0 generated an exception
java.lang.NoClassDefFoundError: fr/mrmicky/fastparticle/ParticleType
        at me.car1ot.moneyitemsrain.ItemsRainClass$2.lambda$0(ItemsRainClass.java:63) ~[?:?]
        at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_232]
        at me.car1ot.moneyitemsrain.ItemsRainClass$2.run(ItemsRainClass.java:61) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-77]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:423) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-77]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Code**
`
FastParticle.spawnParticle(Bukkit.getWorld("world"), ParticleType.REDSTONE, v.getLocation(), 1, Color.GREEN);
`

**Comment by MrMicky-FR** [comment]
You need to shade FastParticles in your plugin jar, if you use Maven you have an exemple in the readme
